import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { useContext, useEffect, useState } from 'react';
import { AppContext } from '../contexts/AppContext';
import Link from 'next/link';
import ImgWrapper from '../components/ImgWrapper/ImgWrapper';
import { getFirestore } from '../utils/firebase';
import { CartContext } from '../contexts/CartContext';
import Hero from '../components/Hero/Hero';
import Navbar from '../components/Navbar/Navbar';

export default function Home() {
  const { cart, setCart } = useContext(CartContext);
  const { items, setItems } = useState([{ name: 'pepe', id: '2323' }]);
  const { loading, setLoading } = useState(true);

  useEffect(() => {
    setCart([
      { id: 1, name: 'Robert' },
      { id: 2, name: 'Mike' },
    ]);
  }, [setCart]);

  useEffect(() => {
    console.log(items);
  }, [items]);

  useEffect(() => {
    const getItems = async () => {
      try {
        const db = getFirestore();
        const itemsCollection = db.collection(`songs`);
        const itemSnapshot = await itemsCollection
          .orderBy('name', 'desc')
          .limit(20)
          .get();

        console.log('Songs:', itemSnapshot);
        const items = itemSnapshot.docs.map((doc) => {
          return { id: doc.id, ...doc.data() };
        });

        // setItems(items);
        // setLoading(false);
        console.log('Songs:', items);
      } catch (error) {
        console.log(error);
      }
    };
    getItems();
  }, [setItems, setLoading]);

  const linkTo = `about`;

  const addProduct = (product) => {
    setCart([...cart, product]);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main className={styles.main}>
        <Hero />

        <ul>
          {cart.map((item) => (
            <li key={item.id}>
              <p>{item.name}</p>
            </li>
          ))}
        </ul>

        {/* <ul>
          {!loading > 0 &&
            songs.map((song) => <li key={song.id}>{song.name}</li>)}
        </ul> */}

        <button onClick={() => addProduct({ name: 'Repasador', id: '34' })}>
          Add Product
        </button>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
          <Link href={`/${linkTo}`}>
            <a>About</a>
          </Link>
        </p>

        <ImgWrapper />

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
